<?php
	
	if (!defined('BASEPATH'))
    exit('No direct script access allowed');
	
	class Programtype_model extends CI_Model
	{
		
		public $table = 'programtype';
		public $id = 'id';
		public $order_asc = 'asc';
		public $order = 'desc';
		
		function __construct()
		{
			parent::__construct();
		}
		
		// get all
		function get_all()
		{
			$this->db->order_by('program_type_description', $this->order_asc);
			return $this->db->get($this->table)->result();
		}
		
		// get data by id
		function get_by_id($id)
		{
			$this->db->where($this->id, $id);
			return $this->db->get($this->table)->row();
		}
		
		function get_by_condition($condition)
		{
			$this->db->order_by($this->id, $this->order);
			$this->db->where($condition);
			return $this->db->get($this->table)->result();
		}

		// insert data
		function insert($data)
		{
			$this->db->set('created_date',date('d/m/Y hh:mm:ss'));
			$this->db->set('created_by','DEFAULT');
			if($this->db->insert($this->table, $data)){
				return $this->id;
			}
			else
			{
				return false;
			}
		}
		
		// update data
		function update($data, $where)
		{

			$this->db->set('updated_date',date('d/m/Y hh:mm:ss'));
			$this->db->set('updated_by','DEFAULT');
			$this->db->where($where);
			if( $this->db->update($this->table, $data)){
				return $this->id;
			}
			else{
				
				return false;
			}
	
		}
		
		// delete data
		function delete($where)
		{
			$this->db->where($where);
			if($this->db->delete($this->table)){
				return $this->id;
			}
			else{
				
				return false;
			}
			
		
		}
		
	}
	
	/* End of file M_room_model.php */
	/* Location: ./application/models/M_room_model.php */
	/* Please DO NOT modify this information : */
	/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-27 17:17:49 */
/* http://harviacode.com */	