<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Report_model extends CI_Model
{

	public $table = 'report';

	public $vtable = 'onar_v_report';
	public $id = 'id';
	public $order = 'desc';

	function __construct()
	{
		parent::__construct();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->vtable)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->vtable)->row();
	}

	function get_report_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->vtable)->result();
	}

	function get_by_condition($condition)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->where($condition);
		return $this->db->get($this->vtable)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->set('created_date', date('Y-m-d H:i:s'));

		$this->db->set('created_by', 'DEFAULT');
		if ($this->db->insert($this->table, $data)) {
			return $this->id;
		} else {
			return false;
		}
	}

	// update data
	function update($data, $where)
	{

		$this->db->set('updated_date', date('Y-m-d H:i:s'));
		$this->db->set('updated_by', 'DEFAULT');
		$this->db->where($where);
		if ($this->db->update($this->table, $data)) {
			return $this->id;
		} else {

			return false;
		}
	}

	// delete data
	function delete($where)
	{
		$this->db->where($where);
		if ($this->db->delete($this->table)) {
			return $this->id;
		} else {

			return false;
		}
	}
}
	
	/* End of file M_room_model.php */
	/* Location: ./application/models/M_room_model.php */
	/* Please DO NOT modify this information : */
	/* Generated by Harviacode Codeigniter CRUD Generator 2016-04-27 17:17:49 */
/* http://harviacode.com */
